Gymlog/Controllers/CardController.cs
using Gymlog.Core.Contracts;
using Gymlog.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using static Gymlog.Constants.MessageConstants;
using static Gymlog.Constants.RoleConstants;

namespace Gymlog.Controllers
{

    public class CardController : BaseController
    {
        private readonly ICardService cardService;
        public CardController(ICardService _cardService)
        {
            cardService = _cardService;
        }

        [Authorize(Roles = AdminRole)]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [Authorize(Roles = AdminRole)]
        [HttpGet]
        public IActionResult ViewCard(int? cardNumber, string? cardId)
        {

            if (cardId != null)
            {
                return RedirectToAction("CheckCard", new { cardId = cardId, check = true });

            }
            else if (cardNumber.HasValue)
            {

                return RedirectToAction("CheckCard", new { cardNumber = cardNumber.Value, cardId = cardId, check = true });
            }


            return View();
        }


        [HttpPost]
        [HttpGet]
        public async Task<IActionResult> CheckCard(int cardNumber, string? cardId, bool check)
        {
            if (cardNumber != null && cardNumber != 0 || cardId != null)
            {
                var model = await cardService.CheckCardAsync(cardNumber, cardId, GetUserId(), check);
                if (model == null)
                {
                    TempData["UserMessageError"] = "Няма карта с този номер!";
                    return RedirectToAction("ViewCard");
                }
                return View(model);
            }
            else
            {
                TempData["UserMessageError"] = "Трябва едно от двете полета да е попълнено!";
                return RedirectToAction("ViewCard");
            }
        }


        //[HttpPost]
        //[HttpGet]
        //public async Task<IActionResult> CheckCard(int cardNumber, string phoneNumber)
        //{
        //    if (cardNumber != 0)
        //    {
        //        var model = await cardService.CheckCardAsync(cardNumber, phoneNumber, GetUserId());
        //        if (model == null)
        //        {
        //            TempData["UserMessageError"] = "Няма карта с този номер";
        //            return RedirectToAction("ViewCard");
        //        }
        //        return RedirectToAction("ViewCard", new { cardNumber = model.Id });
        //    }
        //    else if (!string.IsNullOrEmpty(phoneNumber))
        //    {
        //        var model = await cardService.CheckCardAsync(cardNumber, phoneNumber, GetUserId());
        //        if (model == null)
        //        {
        //            TempData["UserMessageError"] = "Няма потребител с този телефонен номер";
        //            return RedirectToAction("ViewCard");
        //        }
        //        return RedirectToAction("ViewCard", new { cardNumber = model.Id });
        //    }
        //    else
        //    {
        //        TempData["UserMessageError"] = "Трябва едно от двете полета да е попълнено!";
        //        return RedirectToAction("ViewCard");
        //    }
        //}

        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> Create(string firtsName, string lastName, DateTime startData, DateTime endData, string cardId)
        {
            var card = await cardService.CreateAsync(firtsName, lastName, startData, endData, cardId);

            TempData[UserMessageSuccess] = "Картата е добавена";

            return RedirectToAction(nameof(CheckCard), new { cardNumber = card });
        }

        //[HttpGet]
        //public async Task<IActionResult> MyCard()
        //{
        //    var model = await cardService.MyCard(GetUserId());

        //    return View(model);
        //}

        [Authorize(Roles = AdminRole)]
        [HttpGet]
        public async Task<IActionResult> EditCard(int cardId)
        {
            var model = await cardService.GetViewForEdit(cardId);
            if (model == null)
            {
                TempData[UserMessageError] = "Несъществуване такава карта";
                return RedirectToAction(nameof(CheckCard), new { cardNumber = cardId });
            }

            return View(model);
        }

        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> EditCard(EditCard card)
        {
            if (!ModelState.IsValid)
            {
                return View(card);
            }
            await cardService.EditAsync(card);

            TempData[UserMessageSuccess] = "Картата е редактирана";

            return RedirectToAction("CheckCard", new { cardNumber = card.Id, check = false });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteCard(int cardId)
        {
            await cardService.DeleteCardAsync(cardId);

            TempData[UserMessageError] = "Картата е изтрита успешно!";

            return RedirectToAction(nameof(ViewCard));
        }

        [HttpGet]
        public async Task<IActionResult> ViewAllCards(string? searchQuery, string cardStatus = "all")
        {
            ViewData["SearchQuery"] = searchQuery;
            ViewData["CardStatus"] = cardStatus;

            var cards = await cardService.ViewAllCardsAsync(searchQuery, cardStatus);
            return View(cards);
        }

        [HttpGet]
        public async Task<IActionResult> ViewCardHistory(DateTime? data)
        {
            var selectedDate = data ?? DateTime.Now;

            var cards = await cardService.ViewCardHistoryAsync(selectedDate);

            return View(cards);
        }



        private string GetUserId()
        {
            return User.FindFirst(ClaimTypes.NameIdentifier)?.Value ?? string.Empty;
        }
    }
}

Gymlog/Views/Card/CheckCard.cshtml
<!DOCTYPE html>
<html lang="bg">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Кредитна Карта</title>
    <link rel="stylesheet" href="/css/card/myCards.css">
</head>
<body>
    <div class="container">
        <div class="credit-card">
            <div class="card-logo">
                <img src="https://biosportgym.com/wp-content/uploads/2023/05/cropped-cropped-cropped-whitelogo-2-2048x488.png" alt="Card Logo">
                <form asp-action="EditCard" method="get">
                    <input type="hidden" name="cardId" value="@Model.Id" />
                    <button type="submit">Редактирай</button>
                </form>
                <form asp-action="DeleteCard" method="post">
                    <input type="hidden" name="cardId" value="@Model.Id" />
                    <button type="submit" style="color: red">Изтрий</button>
                </form>
            </div>

            <div class="card-number">
                Номер на карта: @Model.Id
            </div>
            <div class="card-holder">
                <label>Картодържател:</label>
                <div>@Model.FirstName @Model.LastName</div>
            </div>
            <div class="card-expiry">
                <label>Валидна от:</label>
                <div>@Model.Start.ToString("MMMM dd, yyyy")</div>
            </div>
            <div class="card-expiry">
                <label>Валидна до:</label>
                <div>@Model.End.ToString("MMMM dd, yyyy")</div>
            </div>
            <div class="in">

                <div class="cardId">
                    <label>id:</label>
                    <div>@Model.CardId</div>
                </div>
                <div class="cardV">
                    <label>Валидност:</label>
                    <span class="valid-dot @(@Model.Valid == "Да" ? "valid-yes" : "valid-no")"></span>
                </div>


            </div>
        </div>

        <div class="visit-info">
            <div class="visit-field">
                <label>Месечни посещения:</label>
                <div>@Model.Мonth</div>
            </div>
            <div class="visit-field">
                <label>Дневни посещения:</label>
                <div>@Model.Daily</div>
            </div>
        </div>
    </div>
</body>
</html>

Gymlog/Views/Card/Create.cshtml
@{
    ViewData["Title"] = "Create Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="/css/card/cardCreate.css">
</head>
<body>

    <div class="card-body">
        <form asp-controller="Card" asp-action="Create" method="post" class="create">
            <header>
                <h1>Добавяне на нова карта</h1>
            </header>

            <div class="field">
                <input type="text" name="firtsName" id="firtsName" placeholder="Име" required>
                <label for="firtsName">Име</label>
            </div>
            <div class="field">
                <input type="text" name="lastName" id="lastName" placeholder="Фамилия" required>
                <label for="lastName">Фамилия</label>
            </div>

            <div class="field">
                <input type="date" id="startData" name="startData" required>
                <label for="startData">От дата:</label>
            </div>
            <div class="field">
                <input type="date" id="endData" name="endData" required>
                <label for="endData">До дата:</label>
            </div>
            <div class="field">
                <input type="text" id="cardId" name="cardId" required>
                <label for="cardId">Card-Id</label>
            </div>

            <input class="button" type="submit" value="Добави">
        </form>
    </div>

</body>
</html>

Gymlog/Views/Card/EditCard.cshtml
@using Gymlog.Core.Models.CardViews
@model EditCard
@{
    ViewData["Title"] = "Edit Card";
}

<!DOCTYPE html>
<html lang="bg">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Кредитна Карта</title>
    <link rel="stylesheet" href="/css/card/editCard.css">
</head>
<body>
    <form asp-action="EditCard" method="post" id="editCardForm">
        <div class="conteiner">
            <div class="credit-card">
                <input type="hidden" name="Id" value="@Model.Id" />
                <div class="card-logo">
                    <img src="https://biosportgym.com/wp-content/uploads/2023/05/cropped-cropped-cropped-whitelogo-2-2048x488.png" alt="Card Logo">
                    <button type="submit" id="saveButton">Запази</button>
                </div>
                <div class="card-number">
                    Номер на карта: @Model.Id
                </div>
                <div class="card-holder">
                    <label for="FullName">Картодържател:</label>
                    <input type="text" id="FullName" name="FullName" value="@Model.FirstName @Model.LastName" />
                </div>
                <div class="card-expiry">
                    <label for="Start">Валидна до:</label>
                    <input type="date" id="Start" name="Start" value="@Model.Start.ToString("yyyy-MM-dd")" />
                </div>
                <div class="card-expiry">
                    <label for="End">Валидна до:</label>
                    <input type="date" id="End" name="End" value="@Model.End.ToString("yyyy-MM-dd")" />
                </div>
                <div class="card-Id">
                    <label for="CardId">Id:</label>
                    <input type="text" id="CardId" name="CardId" value="@Model.CardId"  />
                </div>
            </div>
        </div>
    </form>

    <script>
        document.addEventListener('keydown', function (event) {
            if (event.key === 'Enter') {
                event.preventDefault(); // Предотвратява стандартното поведение на Enter
                document.getElementById('saveButton').click(); // Кликва бутона за запазване
            }
        });
    </script>
</body>
</html>

Gymlog/Views/Card/MyCard.cshtml
@using Gymlog.Core.Models.CardViews
@using static Gymlog.Constants.RoleConstants;
@model MyCardView
@{
    ViewData["Title"] = "My Card";
}

<!DOCTYPE html>
<html lang="bg">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Кредитна Карта</title>
    <link rel="stylesheet" href="/css/card/myCards.css">
</head>
<body>
    <div class="conteiner">
        <div class="credit-card">
            <div class="card-logo">
                <img src="https://biosportgym.com/wp-content/uploads/2023/05/cropped-cropped-cropped-whitelogo-2-2048x488.png" alt="Card Logo">
                @if (User.IsInRole(AdminRole))
                {
                    <a class="nav-link text-dark" asp-area="" asp-controller="Card" asp-action="EditCard" asp-route-cardId="@Model.Id">Редактирай</a>
                }
            </div>
            <div class="card-number">
                Номер на карта: @Model.Id
            </div>
            <div class="card-holder">
                <label>Картодържател</label>
                <div>@Model.FirstName @Model.LastName</div>
            </div>
            <div class="card-expiry">
                <label>Валидна до</label>
                <div>@Model.End.ToString("MMMM dd, yyyy")</div>
            </div>
        </div>
    </div>
</body>
</html>





          

Gymlog/Views/Card/ViewAllCards.cshtml
<!DOCTYPE html>
<html lang="bg">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Кредитни Карти</title>
    <link rel="stylesheet" href="~/css/card/cardTable.css">
</head>
<body>
    <div class="container">
        <form method="get" action="@Url.Action("ViewAllCards", "Card")">
            <input type="text" name="searchQuery" placeholder="Търси по име..." value="@ViewData["SearchQuery"]" />

            <button type="submit">Търси</button>
            <div>
                <input type="radio" id="all" name="cardStatus" value="all" @(ViewData["CardStatus"] as string == "all" ? "checked" : "")>
                <label for="all">Всички</label>

                <input type="radio" id="valid" name="cardStatus" value="valid" @(ViewData["CardStatus"] as string == "valid" ? "checked" : "")>
                <label for="valid">Валидни</label>

                <input type="radio" id="invalid" name="cardStatus" value="invalid" @(ViewData["CardStatus"] as string == "invalid" ? "checked" : "")>
                <label for="invalid">Невалидни</label>
            </div>

        </form>

        <div class="cards-column">
            @foreach (var card in Model)
            {
                <a href="@Url.Action("CheckCard", "Card", new { cardNumber = card.Id })" class="card-link">
                    <div class="credit-card">
                        <div class="card-logo">
                            <img src="https://biosportgym.com/wp-content/uploads/2023/05/cropped-cropped-cropped-whitelogo-2-2048x488.png" alt="Card Logo">
                        </div>
                        <div class="card-number">Номер на карта: @card.Id</div>
                        <div class="card-holder">Картодържател: @card.FirstName @card.LastName</div>
                        <div class="card-expiry">Валидна от: @card.Start.ToString("MMMM dd, yyyy")</div>
                        <div class="card-expiry">Валидна до: @card.End.ToString("MMMM dd, yyyy")</div>
                    </div>
                </a>
            }
        </div>
    </div>
</body>
</html>

Gymlog/Views/Card/ViewCard.cshtml
@{
    ViewData["Title"] = "View Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="/css/card/view.css">
</head>
<body>
    <div class="conteiner">
        <form asp-action="ViewCard" method="get" class="create">
            <header>
                <h1>Регистриране на карта</h1>
            </header>

            <div class="field">
                <input type="text" name="cardNumber" id="card-number" placeholder="Номер на карта">
                <label for="card-number">Номер на карта</label>
            </div>
            <div class="field">
                <input type="text" name="cardId" id="cardId" placeholder="Card Id">
                <label for="cardId">Card Id</label>
            </div>
            <input class="button" type="submit" value="Търси">
        </form>
    </div>
</body>
</html>

Gymlog/Views/Card/ViewCardHistory.cshtml
<!DOCTYPE html>
<html lang="bg">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Кредитни Карти</title>
    <link rel="stylesheet" href="~/css/card/cardTable.css">
    <script>
        function saveDate() {
            var dateInput = document.getElementById('date');
            localStorage.setItem('selectedDate', dateInput.value);
        }

        function loadDate() {
            var savedDate = localStorage.getItem('selectedDate');
            if (savedDate) {
                document.getElementById('date').value = savedDate;
            }
        }

        window.onload = function () {
            loadDate();
        };
    </script>
</head>
<body>
    <div class="container">
        <form method="get" action="ViewCardHistory" onsubmit="saveDate()">
            <div>
                <label for="date">Избери дата:</label>
                <input type="date" id="date" name="data" />
            </div>

            <button type="submit">Търси</button>
        </form>

        <div class="cards-column">
            @if (Model != null)
            {
                @foreach (var card in Model)
                {
                    <a href="@Url.Action("CheckCard", "Card", new { cardNumber = card.Id })" class="card-link">
                        <div class="credit-card">
                            <div class="card-logo">
                                <img src="https://biosportgym.com/wp-content/uploads/2023/05/cropped-cropped-cropped-whitelogo-2-2048x488.png" alt="Card Logo">
                            </div>
                            <div class="card-number">Номер на карта: @card.Id</div>
                            <div class="card-holder">Картодържател: @card.FirstName @card.LastName</div>
                            <div class="card-expiry">Валидна от: @card.Start.ToString("MMMM dd, yyyy")</div>
                            <div class="card-expiry">Валидна до: @card.End.ToString("MMMM dd, yyyy")</div>
                        </div>
                    </a>
                }
            }
            else
            {
                <div class="no-cards">Няма налични карти за показване.</div>
            }
        </div>
    </div>
</body>
</html>